Controllers/TestController.cs
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Data;
using WebApp.Services;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class TestController : Controller
    {
        private readonly INotificationMail _notificationMail;
        private readonly ITestRepos repos;

        public TestController(INotificationMail notificationMail, ITestRepos repos)
        {
            _notificationMail = notificationMail;
            this.repos = repos;
        }
        public IActionResult Index()
        {
            //var result = ctx.Products.ToList();
            return View();
        }
        [HttpGet("notification")]
        //[Authorize(AuthenticationSchemes=JwtBearerDefaults.AuthenticationScheme)]
        public IActionResult Notification()
        {
            return View();
        }
        [HttpPost("notification")]
        public IActionResult Notification(NotificationViewModel model)
        {
            if (ModelState.IsValid)
            {
                _notificationMail.SendNotification("shirohige538@gmail.com", "Thank You For Registering Our Notifications", $"From: {model.Name}");
                ViewBag.UserMessage = "Notification Mail Sent";
                ModelState.Clear();
            }
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Store()
        {
            var display = repos.GetProducts();
            return View(display);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>What's Up, @ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="~/lib/fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet"/>
    <link href="~/css/font.css?v=1.1" rel="stylesheet" />
    @RenderSection("head", false)
</head>
<body>
    <header class="container">
        <nav class="navbar navbar-expand-md">
            <h3 class="navbar-brand"><i class="fas fa-user-secret"></i> Heyo, @ViewBag.Title</h3>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#testMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="testMenu" class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" asp-controller="Test" asp-action="Index">Index</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Test" asp-action="Notification">Notification Register</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Test" asp-action="About">About Us</a></li>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                    else
                    {
                        <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <section class="container">
        @RenderBody()
    </section>
    <footer class="container"><div class="text-center">Nothing To Read Here</div></footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/test.js"></script>
@RenderSection("Scripts", false)
</body>
</html>